VetRegister/Controllers/SpecieController.cs
using Microsoft.AspNetCore.Mvc;
using VetRegister.Core.Contracts;
using VetRegister.Core.Models.Specie;
using VetRegister.Infrastructure.Data.Models;

namespace VetRegister.Controllers
{
    public class SpecieController : Controller
    {
        private readonly ISpecieService specieService;

        public SpecieController(ISpecieService specieService)
        {
            this.specieService = specieService;
        }


        public async Task<IActionResult> All()
        {
            return View(new SpecieFormModel
            {
                AllSpeciesList = await specieService.GetAllSpeciesAsync()
            });
        }

        [HttpPost]
        public async Task<IActionResult> All(SpecieFormModel modelSpecie)
        {
            if (await specieService.SpecieNameExistsAsync(modelSpecie.NewSpecieName))
            {
                this.ModelState.AddModelError(nameof(Specie.Id), "Specie already exists.");
            }

            if (ModelState.IsValid == false)
            {
                modelSpecie.AllSpeciesList = await specieService.GetAllSpeciesAsync();
                return View(modelSpecie);
            }

            await specieService.AddSpecieAsync(modelSpecie.NewSpecieName);

            return RedirectToAction("All");
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (await specieService.SpecieIdExistsAsync(id) == false)
            {
                return BadRequest();
            }

            await specieService.DeleteSpecieAsync(id);

            return RedirectToAction("All");
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (await specieService.SpecieIdExistsAsync(id) == false)
            {
                return BadRequest();
            }

            var currentSpecie = await specieService.GetSpecieByIdAsync(id);
            return View(new SpecieFormModel
            {
                NewSpecieName = currentSpecie.Name
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, SpecieFormModel modelSpecie)
        {
            if (ModelState.IsValid == false)
            {
                return View(modelSpecie);
            }

            var currentSpecie = await specieService.GetSpecieByIdAsync(id);
            if (currentSpecie == null)
            {
                return BadRequest();
            }

            await specieService.EditSpecieAsync(currentSpecie, modelSpecie);

            return RedirectToAction("All");
        }
    }
}

VetRegister/Views/Specie/All.cshtml
@model SpecieFormModel 

@{ 
    ViewData["Title"] = "All Species";
}

<form method="post">
    <br>
    <label class="text-body">Existing species:</label>
    <br>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th scope="col">
                    <label>Specie Name</label>
                </th>
                <th scope="col">
                    <label>Specie Modify</label>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var specie in Model.AllSpeciesList)
            {
                <tr>
                    <td>@specie.Name</td>
                    <td>
                        <a class="btn btn-primary" asp-controller="Specie" asp-action="Edit" asp-route-id="@specie.Id">Edit</a>
                        <a class="btn btn-primary" asp-controller="Specie" asp-action="Delete" asp-route-id="@specie.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br>

    <div class="form-group">
        <label class="text-body">Add new specie:</label>
        <input asp-for="NewSpecieName" class="form-control" placeholder="Give me new specie">
        <span asp-validation-for="NewSpecieName" class="small text-danger"></span>
    </div>
    <input class="btn btn-primary float-right" type="submit" value="Save" />

</form>

VetRegister/Views/Specie/Edit.cshtml
@model SpecieFormModel

@{
    ViewData["Title"] = "Edit Specie";
}

<form method="post">
    <br>
    <div class="form-group">
        <label class="text-body">Edit specie:</label>
        <input asp-for="NewSpecieName" class="form-control" placeholder="Give me new specie">
        <span asp-validation-for="NewSpecieName" class="small text-danger"></span>
    </div>
    <input class="btn btn-primary float-right" type="submit" value="Save" />
</form>

VetRegister/Views/Specie/Exists.cshtml
<h2 class="text-danger">This Specie already exists.</h2>