VetRegister/Controllers/AnimalController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VetRegister.Core.Contracts;
using VetRegister.Core.Models.Animal;

namespace VetRegister.Controllers
{
    public class AnimalController : Controller
    {
        private readonly IAnimalService animalService;
        private readonly ISpecieService specieService;
        private readonly IOwnerService ownerService;
        private readonly IDoctorService doctorService;


        public AnimalController(IAnimalService animalService, ISpecieService specieService, IOwnerService ownerService, IDoctorService doctorService)
        {
            this.animalService = animalService;
            this.specieService = specieService;
            this.ownerService = ownerService;
            this.doctorService = doctorService;
        }

        public async Task<IActionResult> Add()
        {
            return View(new AnimalFormModel
            {
                Species = await specieService.GetAllSpeciesAsync()
            });
        }

        [HttpPost]
        public async Task<IActionResult> Add(AnimalFormModel modelAnimal)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (userId == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                modelAnimal.Species = await specieService.GetAllSpeciesAsync();
                return View(modelAnimal);
            }

            if (await specieService.SpecieIdExistsAsync(modelAnimal.SpecieId) == false)
            {
                return BadRequest();
            }

            await animalService.AddAnimalAsync(modelAnimal, userId);

            return RedirectToAction("All");
        }


        public async Task<IActionResult> Edit(int id)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return BadRequest();
            }

            var ownerId = await ownerService.GetOwnerIdAsync(userId);
            if (ownerId == null)
            {
                return BadRequest();
            }

            var currentAnimal = await animalService.GetAnimalIncludeOwnerAsync(id);
            if (currentAnimal == null)
            {
                return BadRequest();
            }

            //if (currentAnimal.Owner.Id != ownerId)
            //    {
            //    return BadRequest();
            //}

            return View(new AnimalFormModel
            {
                Name = currentAnimal.Name,
                DateOfBirth = currentAnimal.DateOfBirth.ToString("d"),
                SpecieId = currentAnimal.SpecieId,
                Species = await specieService.GetAllSpeciesAsync(),
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AnimalFormModel modelAnimal)
        {

            if (await animalService.AnimalIdExistsAsync(id) == false)
            {
                return BadRequest();
            }

            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return BadRequest();
            }

            var ownerId = ownerService.GetOwnerIdAsync(userId);
            if (ownerId == null)
            {
                return BadRequest();
            }

            //if (currentAnimal.Owner.Id != ownerId)
            //{
            //    return BadRequest();
            //}

            await animalService.EditAnimalAsync(id, modelAnimal);

            return RedirectToAction("All");
        }


        public async Task<IActionResult> Details(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return BadRequest();
            }

            //Any doctor should be able to view details, so he can add procedure, not just owner !!!
            
            if (await animalService.AnimalIdExistsAsync(id) == false)
            {
                return BadRequest();
            }

            //if (currentAnimal.Owner.Id != ownerId) //do not forget include owner
            //{
            //    return BadRequest();
            //}

            var currentAnimal = await animalService.GetAnimalAsync(id);

            return View(new AnimalViewModel
            {
                Id = currentAnimal!.Id,
                Name = currentAnimal!.Name,
                DateOfBirth = currentAnimal!.DateOfBirth.ToString("d"),
                Age = (DateTime.UtcNow.Year - currentAnimal!.DateOfBirth.Year).ToString(),
                SpecieId = currentAnimal!.SpecieId,
                SpecieName = await specieService.GetSpecieNameAsync(currentAnimal!.SpecieId),
                Procedures = await animalService.GetAnimalProceduresAsync(currentAnimal!.Id)
            });
        }


        public async Task<IActionResult> Delete(int id)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return BadRequest();
            }

            var ownerId = await ownerService.GetOwnerIdAsync(userId);
            if (ownerId == null)
            {
                return BadRequest();
            }

            if (await animalService.AnimalIdExistsAsync(id) == false)
            {
                return BadRequest();
            }

            //if (currentAnimal.OwnerId != ownerId)
            //{
            //    return BadRequest();
            //}

            await animalService.DeleteAnimalAsync(id);

            return RedirectToAction("All");
        }


        public async Task<IActionResult> All(string? nameFilter, int? specieFilter, string? dateOfBirthFilter, string? ageFilter)
        {
            return View( await animalService.GetAllAnimalsAsync(nameFilter, specieFilter, dateOfBirthFilter, ageFilter));
        }
    }
}

VetRegister/Controllers/ClinicController.cs
using Microsoft.AspNetCore.Mvc;
using VetRegister.Core.Contracts;
using VetRegister.Core.Models.Clinic;
using VetRegister.Infrastructure.Data.Models;

namespace VetRegister.Controllers
{
    public class ClinicController : Controller
    {
        private readonly IClinicService clinicService;

        public ClinicController(IClinicService clinicService)
        {
            this.clinicService = clinicService;
        }

        public IActionResult Add()
        {
            ViewBag.ClinicNameExists = false;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(ClinicFormModel modelClinic)
        {
            ViewBag.ClinicNameExists = false;
            if ((await clinicService.ClinicNameTakenAsync(modelClinic.Name)) == true)
            {
                ViewBag.ClinicNameExists = true;
                return View(modelClinic);
            }

            if (ModelState.IsValid == false)
            {
                return View(modelClinic);
            }

            await clinicService.AddClinicAsync(modelClinic);

            return RedirectToAction("All");
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (await clinicService.ClinicIdExistsAsync(id) == false)
            {
                return BadRequest();
            }

            var currentClinic = await clinicService.GetClinicByIdAsync(id);

            var modelClinic = new ClinicFormModel
            {
                Name = currentClinic!.Name,
                PhoneNumber = currentClinic!.PhoneNumber
            };

            return View(modelClinic);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, ClinicFormModel modelClinic)
        {
            
            if (await clinicService.ClinicIdExistsAsync(id) == false)
            {
                return BadRequest();
            }

            await clinicService.EditClinicAsync(id, modelClinic);

            return RedirectToAction(nameof(All));
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (await clinicService.ClinicIdExistsAsync(id) == false)
            {
                return BadRequest();
            }

           if (await clinicService.ClinicHasAnyDoctorsAsync(id) == true)
            {
                return BadRequest(); //clinic has doctors
            }

            await clinicService.DeleteClinicAsync(id);

            return RedirectToAction("All");
        }

        public async Task<IActionResult> Details(int id)
        {
            //var currentClinic = clinicService.GetByIdIncludeDoctors(id);
            var currentClinic = await clinicService.GetClinicByIdAsync(id);

            if (currentClinic == null)
            {
                return BadRequest();
            }

            return View(new ClinicViewModel
            {
                Id = currentClinic.Id,
                Name = currentClinic.Name,
                PhoneNumber = currentClinic.PhoneNumber,
                DoctorNames = await clinicService.GetDoctorNamesForClinicAsync(id)
                //Doctors = currentClinic.Doctors.Select(x =>  x.Name).ToList()
            });;
        }

        public async Task<IActionResult> All()
        {
            return View(await clinicService.GetAllClinicsAsync());
        }
    }
}

VetRegister/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VetRegister.Core.Contracts;
using VetRegister.Core.Models.Doctor;
using VetRegister.Infrastructure.Data.Models;

namespace VetRegister.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctorService doctorService;
        private readonly IProcedureService procedureService;
        private readonly IClinicService clinicService;

        public DoctorController(IDoctorService doctorService, IProcedureService procedureService, IClinicService clinicService)
        {
            this.doctorService = doctorService;
            this.procedureService = procedureService;
            this.clinicService = clinicService;
        }

        public async Task<IActionResult> All()
        {
            return View(await doctorService.GetAllDoctorsAsync());
        }

        public async Task<IActionResult> Details(int id) 
        {
            if (await doctorService.DoctorExistsAsync(id) == false)
            {
                return BadRequest();
            }

            return View(await doctorService.GetDoctorDetailsAsync(id));
        }

        public async Task<IActionResult> Become()
        {
            return View(new BecomeDoctorFormModel
            {
                Clinics = await clinicService.GetAllClinicsAsync()
            });
        }

        [HttpPost]
        public async Task<IActionResult> Become(BecomeDoctorFormModel doctor)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (userId == null)
            {
                return BadRequest();
            }

            if (ModelState.IsValid == false)
            {
                doctor.Clinics = await clinicService.GetAllClinicsAsync();
                return View(doctor);
            }

            var newDoctor = new Doctor
            {
                Name = doctor.Name,
                UserId = userId,
                ClinicId = doctor.ClinicId,
            };

            await doctorService.CreateDoctorAsync(newDoctor);

            return RedirectToAction("Index", "Home");
        }

    }
}

VetRegister/Controllers/OwnerController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VetRegister.Core.Contracts;
using VetRegister.Core.Models.Owner;
using VetRegister.Infrastructure.Data.Models;

namespace VetRegister.Controllers
{
    public class OwnerController : Controller
    {
        private readonly IOwnerService ownerService;

        public OwnerController(IOwnerService ownerService)
        {
                this.ownerService = ownerService;
        }

        public IActionResult All()
        {
            return View(ownerService.GetAllOwnersAsync());
        }

        public IActionResult Details(int id)
        {
            return View(ownerService.GetOwnerDetailsAsync(id));
        }

        public IActionResult Become()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Become(BecomeOwnerFormModel owner)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (userId == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View(owner);
            }

            var newOwner = new Owner
            {
                UserId = userId,
                Address = owner.Address,
                PhoneNumber = owner.PhoneNumber
            };

            ownerService.CreateOwnerAsync(newOwner);

            return RedirectToAction("Index", "Home");
        }
    }
}

VetRegister/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VetRegister</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VetRegister</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="All">Animal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Specie" asp-action="All">Specie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clinic" asp-action="All">Clinic</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Procedure" asp-action="All">Procedure</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="All">Doctor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Owner" asp-action="All">Owner</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - VetRegister - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VetRegister/Views/Shared/_Layout_OLD.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VetRegister</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VetRegister.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VetRegister</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - VetRegister - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>