VetRegister/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VetRegister.Core.Contracts;
using VetRegister.Core.Models.Doctor;
using VetRegister.Infrastructure.Data.Models;

namespace VetRegister.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctorService doctorService;
        private readonly IProcedureService procedureService;
        private readonly IClinicService clinicService;

        public DoctorController(IDoctorService doctorService, IProcedureService procedureService, IClinicService clinicService)
        {
            this.doctorService = doctorService;
            this.procedureService = procedureService;
            this.clinicService = clinicService;
        }

        public async Task<IActionResult> All()
        {
            return View(await doctorService.GetAllDoctorsAsync());
        }

        public async Task<IActionResult> Details(int id) 
        {
            if (await doctorService.DoctorExistsAsync(id) == false)
            {
                return BadRequest();
            }

            return View(await doctorService.GetDoctorDetailsAsync(id));
        }

        public async Task<IActionResult> Become()
        {
            return View(new BecomeDoctorFormModel
            {
                Clinics = await clinicService.GetAllClinicsAsync()
            });
        }

        [HttpPost]
        public async Task<IActionResult> Become(BecomeDoctorFormModel doctor)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (userId == null)
            {
                return BadRequest();
            }

            if (ModelState.IsValid == false)
            {
                doctor.Clinics = await clinicService.GetAllClinicsAsync();
                return View(doctor);
            }

            var newDoctor = new Doctor
            {
                Name = doctor.Name,
                UserId = userId,
                ClinicId = doctor.ClinicId,
            };

            await doctorService.CreateDoctorAsync(newDoctor);

            return RedirectToAction("Index", "Home");
        }

    }
}

VetRegister/Controllers/ProcedureController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VetRegister.Core.Contracts;
using VetRegister.Core.Models.Procedure;

namespace VetRegister.Controllers
{
    public class ProcedureController : Controller
    {
        private readonly IProcedureService procedureService;
        private readonly IDoctorService doctorService;

        public ProcedureController(IProcedureService procedureService, IDoctorService doctorService)
        {
            this.procedureService = procedureService;
            this.doctorService = doctorService;

        }
        public async Task<IActionResult> All()
        {
            return View(await procedureService.GetAllProceduresAsync());
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(ProcedureFormModel modelProcedure, int animalId)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return BadRequest();
            }

            var doctorId = await doctorService.GetDoctorIdAsync(userId);
            if (doctorId == null) 
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View(modelProcedure);
            }

            await procedureService.AddProcedureAsync(modelProcedure, animalId, (int)doctorId); // casting to int as it is already checked that it is not null

            return RedirectToAction("All");
        }
    }
}

VetRegister/Views/Doctor/All.cshtml
@model IEnumerable<DoctorViewModel>

@{
    ViewData["Title"] = "All Doctors";
}

<form>
    <br>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th scope="col">
                    <label>Doctor Name</label>
                </th>
                <th scope="col">
                    <label>Doctor's Clinic</label>
                </th>
                <th scope="col">
                    <label>Procedures done</label>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var doctor in Model)
            {
                <tr>
                    <td>@doctor.Name</td>
                    <td>@doctor.ClinicName</td>
                    <td>@doctor.ProceduresCount</td>
                    <td>
                        <a class="btn btn-primary" asp-controller="Doctor" asp-action="Details" asp-route-id="@doctor.Id">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

VetRegister/Views/Doctor/Become.cshtml
@model BecomeDoctorFormModel

@{
    ViewData["Title"] = "Become Doctor";
}

<form method="post">

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" placeholder="Doctor Full Name">
    </div>
    <div class="form-group">
        <label asp-for="ClinicId"></label>
        <select asp-for="ClinicId" class="form-control">
            @foreach (var clinic in Model.Clinics)
            {
                <option value="@clinic.Id">@clinic.Name</option>
            }
        </select>
    </div>
    <input class="btn btn-primary float-right" type="submit" value="Save" />
</form>

VetRegister/Views/Doctor/Details.cshtml
@model DoctorViewModel

@{
    ViewData["Title"] = "Doctor Details";
}

<form>
    <div class="form-group row">
        <label for="Name" class="col-sm-2 col-form-label">Doctor Name:</label>
        <a for="Name" class="col-sm-10 col-form-label">@Model.Name</a>
    </div>
    <div class="form-group row">
        <label for="Clinic Name" class="col-sm-2 col-form-label">Clinic Name:</label>
        <a for="Age" class="col-sm-10 col-form-label">@Model.ClinicName</a>
    </div>
    <br>


    <div>
        <br>
        <label class="text-body">Procedures done by doctor @Model.Name:</label>
        <br>
    </div>


    <br>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th scope="col">
                    <label>Date</label>
                </th>
                <th scope="col">
                    <label>Description</label>
                </th>
                <th scope="col">
                    <label>Animal</label>
                </th>
                <th scope="col">
                    <label>Details</label>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var procedure in Model.Procedures)
            {
                <tr>
                    <td>@procedure.CreatedOn</td>
                    <td>@procedure.Description</td>
                    <td>@procedure.AnimalName</td>
                    <td>
                        <a class="btn btn-primary" asp-controller="Procedure" asp-action="Details" asp-route-id="@procedure.Id">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br>



    <br>
    <div>
        <a class="btn btn-primary" asp-controller="Doctor" asp-action="All">Back to All Doctors</a>
    </div>



</form>